Display AOVs rework
tangent-opensource/hdBlackbird pull request #162
Opened 2021-05-04 19:44 UTC by dedoardo

This patch introduces the following changes when rendering in non-tiled mode. It requires [this Cycles PR](https://github.com/tangent-opensource/cycles/pull/42).
- Aov's render buffers are now updated once a rendering pass has finished through the new callback
- Blitting render buffers is faster and not tied to `RenderPass::_Execute` anymore. On the other hand it runs exclusively with rendering. Responsiveness doesn't seem to be affected negatively
- Misc improvements to `HdRenderBuffer`.
  - Memory is actually deallocated on deallocate
  - Deletion of an output buffer forces rendering to be interrupted earlier (this could help responsiveness)
  - Access is not synchronized with resize / delete operations  
  - (Working on this) Better lifetime management with the renderparam

The patch is currently stable, I do not experience crashes when switching to different AOVs, but some polishing is missing:
- Simplification of the synchronization / lifetime management code. There is still lots of unused code floating around
- Testing all the aovs. Some type conversions could not be implemented , need to go through all the possible bindable AOVs

The tiled and adaptive code path could be further unified together, this is a first step.

2021-05-11 16:17 UTC, bareya commented on plugin/hdCycles/renderParam.cpp
> +                TF_WARN("Unsupported component type %d for aov %s ", (int)rb->GetFormat(), aov.aovName.GetText());
As a small comment I would rely on C++ static_cast feature, rather than old style c-style casts. Those casts happen at runtime without any checks. I strongly recommend using static_casts.

2021-05-17 23:19 UTC, dedoardo commented
Thinking about it, the fact that we see a lower resolution frame earlier should mean that it's more responsive.

2021-05-18 18:17 UTC, boberfly commented
Doing a stress-test here @dedoardo and adding/removing a bunch of AOVs seems to work great, no crashes. It does get slower the more AOVs you load in but that's definitely to be expected, it feels fast enough with Houdini's default color+depth+normal loaded in though and we can be mindful of making custom viewport settings which don't load all AOVs at once in the default case...

My little patch tweak uses ccl::PASS_DEPTH instead of ccl::PASS_MIST and we discovered it wasn't quite what Hydra expects and has a weird default of the depth value set to 100.0f instead of 1.0f (which threw off the camera tumble code in the viewport, which must use depth for camera calculations).

Awesome work @dedoardo !

2021-05-18 23:17 UTC, boberfly commented
Just an update, the depth seems to work on windows but I am not sure why linux doesn't seem to work quite right yet...

2021-05-19 10:29 UTC, skwerner requested changes
Can you run clang-format on this patch?

2021-05-19 10:29 UTC, skwerner commented on plugin/hdCycles/renderBuffer.cpp
> +    m_mutex.lock();
Scoped lock

2021-05-19 10:29 UTC, skwerner commented on plugin/hdCycles/renderBuffer.cpp
> +    m_mutex.lock();
scoped lock

2021-05-19 10:29 UTC, skwerner commented on plugin/hdCycles/renderBuffer.cpp
> +    m_mutex.lock();
scoped lock

2021-05-19 14:48 UTC, dedoardo commented
Thanks for reviewing @skwerner, ran clang-format and changed the scoped lock.

2021-05-19 16:47 UTC, boberfly commented
Hey I've got a screenshot of the latest patch here side by side windows vs linux, not sure why the grid doesn't get culled on the linux side (visually the AOVs are being made when I toggle depth/normal so they do exist and are working):
![depth_windows](https://user-images.githubusercontent.com/5601445/118852039-01393c00-b898-11eb-9a0e-f5f189150b54.PNG)

2021-05-19 21:10 UTC, dedoardo commented
After the discussion today I am merging this for now and keeping #111 alive, making it linux specific

2021-05-19 21:12 UTC, merged